//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZophopWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tracker
    {
        public tracker()
        {
            this.points = new HashSet<point>();
        }
    
        public long ID { get; set; }
        public long UserID { get; set; }
        public Nullable<long> IMEI { get; set; }
        public string Name { get; set; }
        public string Comment { get; set; }
        public long IconID { get; set; }
        public string HistoryColor { get; set; }
        public long Period { get; set; }
        public long SleepPeriod { get; set; }
        public string Phone { get; set; }
        public long ParkRadius { get; set; }
        public long MinParkTime { get; set; }
        public long DaysToStore { get; set; }
        public bool Enable { get; set; }
        public long Number { get; set; }
        public long MaxSpeed { get; set; }
        public long AlarmParkTime { get; set; }
        public string DeviceType { get; set; }
        public float FuelExpenseHr { get; set; }
        public long CreateDate { get; set; }
        public long InstallDate { get; set; }
        public string StateNumber { get; set; }
        public string InstallerName { get; set; }
        public long MinIdleTime { get; set; }
        public float MinDrain { get; set; }
        public string Flags { get; set; }
        public string servergroup { get; set; }
    
        public virtual ICollection<point> points { get; set; }
    }
}
